apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: lrs
    component: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    app: mongodb
    deploymentconfig: mongodb
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: lrs
        deploymentconfig: mongodb
    spec:
      containers:
      - env:
        - name: MONGODB_ADMIN_PASSWORD
          value: <password>
        - name: MONGODB_DATABASE
          value: mongo
        - name: MONGODB_PASSWORD
          value: <password>
        - name: MONGODB_USER
          value: admin
        image: registry.redhat.io/rhscl/mongodb-34-rhel7@sha256:a9e54d86208f0af8227f41d45559079727715b9b14804037845ffa86f582e4e3
        imagePullPolicy: Always
        name: mongodb
        ports:
        - containerPort: 27017
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mongodb/data
          name: mongodb
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: mongodb
          persistentVolumeClaim:
            claimName: mongodb-storage
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - mongodb
      from:
        kind: ImageStreamTag
        name: mongodb:3.4
        namespace: openshift
    type: ImageChange
