apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    application: lrs
    component: proxy
  name: proxy
spec:
  replicas: 1
  selector:
    deploymentconfig: proxy
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        application: lrs
        component: proxy
        deploymentconfig: proxy
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - $STI_SCRIPTS_PATH/run
        env:
        - name: TZ
          value: US/Eastern
        image: registry.redhat.io/rhscl/nginx-116-rhel7:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: proxy
        ports:
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /opt/app-root/etc/nginx.d/
          name: proxy-config
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          name: proxy-config
        name: proxy-config
      imagePullSecrets:
      - name: 4988366-learn-registry-account-pull-secret
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - proxy
      from:
        kind: ImageStreamTag
        name: nginx-116-rhel7:latest
    type: ImageChange
  - type: ConfigChange
---
apiVersion: v1
kind: ImageStream
metadata:
  name: nginx-116-rhel7
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: registry.redhat.io/rhscl/nginx-116-rhel7
    importPolicy:
      scheduled: true
    name: latest
    referencePolicy:
      type: Source
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: lrs
    component: proxy
  name: proxy
spec:
  ports:
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    deploymentconfig: proxy
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: proxy
  name: proxy
spec:
  host: learning-locker-dev.oscp-dev.partners.org
  port:
    targetPort: 8443-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: proxy
    weight: 100
  wildcardPolicy: None

