apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    build: learning-locker
  name: learning-locker
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: learning-locker:latest
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/LearningLocker/learninglocker.git
      ref: v2.8.2        
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:10
        namespace: openshift
      scripts: https://raw.githubusercontent.com/mghlcs/openshift-learning-locker/master/s2i
    type: Source
  triggers:
  - type: ConfigChange
---
apiVersion: v1
kind: ImageStream
metadata:
  name: learning-locker
spec:
  lookupPolicy:
    local: false
