apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: mongodb
    component: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    app: mongodb
    deploymentconfig: mongodb
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: mongodb
        deploymentconfig: mongodb
    spec:
      containers:
      - env:
        - name: MONGODB_ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: mongodb-admin-password
              name: mongodb-config
        - name: MONGODB_DATABASE
          valueFrom:
            configMapKeyRef:
              key: mongodb-database
              name: mongodb-config
        - name: MONGODB_USER
          valueFrom:
            configMapKeyRef:
              key: mongodb-user
              name: mongodb-config                
        - name: MONGODB_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: mongodb-password
              name: mongodb-config
        imagePullPolicy: Always
        name: mongodb
        ports:
        - containerPort: 27017
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/mongodb/data
          name: mongodb
      volumes:
        - name: mongodb
          persistentVolumeClaim:
            claimName: mongodb-storage
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - mongodb
      from:
        kind: ImageStreamTag
        name: mongodb:3.6
        namespace: openshift
    type: ImageChange
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  ports:
  - name: 27017-tcp
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    deploymentconfig: mongodb
