apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: lrs
    component: proxy
  name: proxy
spec:
  replicas: 1
  selector:
    app: lrs    
    deploymentconfig: proxy
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: lrs
        component: proxy
        deploymentconfig: proxy
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - $STI_SCRIPTS_PATH/run
        env:
        - name: TZ
          value: US/Eastern
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: proxy
        ports:
        - containerPort: 8443
          protocol: TCP
        volumeMounts:
        - mountPath: /opt/app-root/etc/nginx.d/
          name: proxy-config            
          readOnly: true
        - mountPath: /opt/app-root/etc/nginx.ssl/
          name: proxy-ssl
          readOnly: true            
      volumes:
      - name: proxy-ssl
        secret:
          secretName: proxy-ssl
      - configMap:
          name: proxy-config
        name: proxy-config
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - proxy
      from:
        kind: ImageStreamTag
        name: nginx:1.16
        namespace: openshift
    type: ImageChange
  - type: ConfigChange
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lrs
    component: proxy
  name: proxy
spec:
  ports:
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    deploymentconfig: proxy
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: proxy
  name: proxy
spec:
  host: activities.oscp-dev.partners.org
  port:
    targetPort: 8443-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: proxy
    weight: 100
  wildcardPolicy: None
