apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: lrs
    component: redis
  name: redis
spec:
  replicas: 1
  selector:
    name: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lrs
        component: redis
        name: redis
    spec:
      containers:
      - env:
        - name: TZ
          value: US/Eastern
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 6379
          timeoutSeconds: 1
        name: redis
        ports:
        - containerPort: 6379
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - test "$(redis-cli -h 127.0.0.1 ping)" == "PONG"
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 512Mi
        volumeMounts:
        - mountPath: /var/lib/redis/data
          name: redis-eph-data
      volumes:
      - emptyDir: {}
        name: redis-eph-data
  triggers:
  - imageChangeParams:
      automatic: false
      containerNames:
      - redis
      from:
        kind: ImageStreamTag
        name: redis:5
        namespace: openshift
    type: ImageChange
  - type: ConfigChange
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    component: redis
  name: redis
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: redis
