apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: lrs
    component: ui
  name: ui
spec:
  replicas: 1
  selector:
    app: lrs
    deploymentconfig: ui
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: lrs
        component: ui
        deploymentconfig: ui
    spec:
      containers:
      - env:
        - name: NPM_RUN
          value: "start-ui-server"
        - name: NODE_ENV
          value: "production"
        - name: UI_PORT
          value: "3000"
        - name: API_PORT
          value: "8080"
        - name: MONGODB_PATH
          valueFrom:
            configMapKeyRef:
              key: mongodb-path
              name: mongodb-config
        - name: QUEUE_PROVIDER
          value: "REDIS"
        - name: FS_REPO
          value: "local"
        - name: REDIS_HOST
          value: "redis.learning-locker-dev.svc.cluster.local"
        - name: REDIS_DB
          value: "0"
        - name: APP_SECRET
          valueFrom:
            configMapKeyRef:
              key: app-secret
              name: app-config
        - name: SMTP_HOST
          valueFrom:
            configMapKeyRef:
              key: smtp-host
              name: app-config
        - name: SMTP_PORT
          valueFrom:
            configMapKeyRef:
              key: smtp-port
              name: app-config
        - name: SMTP_SECURED
          valueFrom:
            configMapKeyRef:
              key: smtp-secured
              name: app-config
        - name: SMTP_USER
          valueFrom:
            configMapKeyRef:
              key: smtp-user
              name: app-config
        - name: SMTP_PASS
          valueFrom:
            configMapKeyRef:
              key: smtp-pass
              name: app-config                
        image: learning-locker:latest
        name: ui
        ports:
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 25
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3000
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /opt/app-root/src/learninglocker/storage 
          name: storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
  triggers:
  - imageChangeParams:
      automatic: false
      containerNames:
      - ui
      from:
        kind: ImageStreamTag
        name: learning-locker:latest
    type: ImageChange
  - type: ConfigChange
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lrs
    component: ui
  name: ui
spec:
  ports:
  - name: 3000-tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    deploymentconfig: ui
