apiVersion: v1
kind: ImageStream
metadata:
  name: xapi
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: learninglocker/xapi-service:latest
    generation: 1
    importPolicy:
      scheduled: true
    name: latest
    referencePolicy:
      type: Source
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: lrs
    component: xapi
  name: xapi
spec:
  replicas: 1
  selector:
    app: lrs
    deploymentconfig: xapi
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: lrs
        component: xapi        
        deploymentconfig: xapi
    spec:
      containers:
      - env:
        - name: MONGO_URL
          value: "mongodb://mongo:mongopass@mongodb.learning-locker-dev.svc.cluster.local:27017/mongo"
        - name: STORAGE_REPO
          value: "local"
        - name: REDIS_HOST
          value: "redis.learning-locker-dev.svc.cluster.local/0"
        name: xapi
        ports:
        - containerPort: 8081
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/src/app/storage
          name: xapi-storage              
      volumes:
      - name: xapi-storage
        persistentVolumeClaim:
          claimName: xapi-storage      
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - xapi
      from:
        kind: ImageStreamTag
        name: xapi:latest
    type: ImageChange
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lrs
  name: xapi
spec:
  ports:
  - name: 8081-tcp
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    deploymentconfig: xapi
