apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    application: learning-locker
    component: proxy
  name: proxy
spec:
  replicas: 1
  selector:
    deploymentconfig: proxy
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        application: hublms
        component: proxy
        deploymentconfig: proxy
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - $STI_SCRIPTS_PATH/run
        env:
        - name: TZ
          value: US/Eastern
        image: registry.redhat.io/rhscl/nginx-116-rhel7:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: proxy
        ports:
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /opt/app-root/etc/nginx.ssl/
          name: proxy-ssl
          readOnly: true
        - mountPath: /opt/app-root/etc/nginx.d/
          name: proxy-config
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: proxy-ssl
        secret:
          secretName: proxy-ssl
      - configMap:
          name: proxy-config
        name: proxy-config
      imagePullSecrets:
      - name: 4988366-learn-registry-account-pull-secret
  test: false
  triggers:
  - imageChangeParams:
      automatic: false
      containerNames:
      - proxy
      from:
        kind: ImageStreamTag
        name: nginx-116-rhel7:latest
    type: ImageChange
  - type: ConfigChange
