apiVersion: v1
kind: Service
metadata:
  labels:
    application: hublms
    component: media
  name: media
spec:
  ports:
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    deploymentconfig: media
  sessionAffinity: None
  type: ClusterIP

