apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: learning-locker-builder
  name: learning-locker-builder
spec:
  output:
    to:
      kind: ImageStreamTag
      name: learning-locker-builder:latest  
  source:
    type: Git
    git:
      ref: master
      uri: https://github.com/mghlcs/openshift-learning-locker
    contextDir: app-builder-image/
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:10
        namespace: openshift
  triggers:
  - type: ConfigChange
  - imageChange:
      type: ImageChange
